Traceback (most recent call last):
  File "/Users/tsauter/venv/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/tsauter/venv/lib/python3.7/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/tsauter/venv/lib/python3.7/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/tsauter/venv/lib/python3.7/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/Users/tsauter/venv/lib/python3.7/site-packages/nbclient/client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/tsauter/venv/lib/python3.7/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/tsauter/venv/lib/python3.7/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Integrate the EBM and store the values
yrs, Ts289, dT, netQ = ebm_ice_albedo_stochastic_ECS(289, Q=342, Cw=2*10**8, \
                                                     alpha=0.30, tau=0.608, years=50)


# Calculate the ECS from the regression line and print the result
print('The ECS is {:.2f} ÂºC'.format(-b/m))
print('The feedback factor is {:.2f}, which implies a negative feedback'.format(-m/b))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/tt/q4k5594x1tz82j1yrmtkdw080000gn/T/ipykernel_3445/1195436669.py[0m in [0;36m<module>[0;34m[0m
[1;32m      5[0m [0;34m[0m[0m
[1;32m      6[0m [0;31m# Calculate the ECS from the regression line and print the result[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 7[0;31m [0mprint[0m[0;34m([0m[0;34m'The ECS is {:.2f} ÂºC'[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0;34m-[0m[0mb[0m[0;34m/[0m[0mm[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0m
[0m[1;32m      8[0m [0mprint[0m[0;34m([0m[0;34m'The feedback factor is {:.2f}, which implies a negative feedback'[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0;34m-[0m[0mm[0m[0;34m/[0m[0mb[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'b' is not defined
NameError: name 'b' is not defined

